name: 3 - Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/3_reusable_workflow.yaml        # Local yaml need to be called without reference/tag/versin
    # uses: owner/repo/.github/workflows/reusable-workflow.yml@main
    with:
      example_input: 'Hello, World!'
    secrets:
      example_secret: ${{ secrets.API_KEY }}
