name: 11.2 - Use Custom Compsite Github Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        
      - name: Use Private Action
        id: foo
        uses: ./composite_action
        with:
          who-to-greet: 'Mona the Octocat'
          
      - name: Display the Random Number
        run: |
          echo "Random number: $RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}