name: 1.2 Trigger - Tags

on:
  push:
    tags:
      - 'v*.*.*'   # This will match any tags like v1.0.0, v2.3.4, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          echo "Building version ${{ github.ref }}"