name: 6 - Secrets

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Use secret in a script
        run: echo "My secret value is ${{ secrets.API_KEY }}"
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create an issue
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"title": "Automated Issue", "body": "This issue was created using GITHUB_TOKEN."}' \
          https://api.github.com/repos/${{ github.repository }}/issues