name: 8 - Artifacts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  ARTIFACT_WHOLE_PATH: artifacts/file.txt
  ARTIFACT_FOLDER_PATH: artifacts/

jobs:
  job_1:
    name: Upload File
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact Directory
        run: mkdir -p ${{ env.ARTIFACT_FOLDER_PATH }}  # Create the directory if it doesn't exist
      - name: Create the file in the directory
        run: echo "Hello World" > ${{ env.ARTIFACT_WHOLE_PATH }}
      - uses: actions/upload-artifact@v4
        with:
          name: file
          path: ${{ env.ARTIFACT_WHOLE_PATH }}
          retention-days: 5

  job_2:
    name: Download File
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: file
          path: ${{ env.ARTIFACT_FOLDER_PATH }}
      - name: List files in the current directory
        run: ls -al ${{ env.ARTIFACT_FOLDER_PATH }}  # This step helps you see where the artifact is downloaded
      - run: cat ${{ env.ARTIFACT_WHOLE_PATH }}